# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# ============ ZSH Quality of Life Settings ============

# History improvements
export HISTSIZE=10000              # Number of commands to keep in memory
export SAVEHIST=10000              # Number of commands to save to file
export HISTFILE=~/.zsh_history
setopt HIST_IGNORE_DUPS           # Don't record duplicate commands
setopt HIST_FIND_NO_DUPS          # Don't show duplicates when searching
setopt HIST_IGNORE_SPACE          # Don't record commands starting with space
setopt SHARE_HISTORY              # Share history between terminal sessions
setopt EXTENDED_HISTORY           # Save timestamp and duration

# Directory navigation
setopt AUTO_CD                    # Type directory name to cd into it
setopt AUTO_PUSHD                 # Push directories onto stack automatically
setopt PUSHD_IGNORE_DUPS         # Don't push duplicate directories
setopt PUSHD_MINUS                # Use - instead of + for directory stack

# Command line editing
setopt INTERACTIVE_COMMENTS       # Allow comments in interactive shell
setopt NO_BEEP                    # Disable terminal beep

# Useful aliases
alias ll='ls -lah'                # Long list with hidden files
alias la='ls -A'                  # All files except . and ..
alias l='ls -CF'                  # Classify files with indicators
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias mkdir='mkdir -pv'          # Create parent dirs as needed, verbose
alias grep='grep --color=auto'   # Always colorize grep
alias df='df -h'                  # Human-readable disk usage
alias du='du -h'                  # Human-readable file sizes
alias history='history -i'        # Show timestamps in history
alias path='echo $PATH | tr ":" "\n"'  # Show PATH in readable format

# Git aliases (in addition to oh-my-zsh git plugin)
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log --oneline --graph --decorate -20'
alias gla='git log --oneline --graph --decorate --all -20'

# Quick navigation shortcuts
alias dev='cd ~/Development'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias docs='cd ~/Documents'

# Safety nets
alias rm='rm -i'                  # Confirm before removing
alias cp='cp -i'                  # Confirm before overwriting
alias mv='mv -i'                  # Confirm before overwriting

# Reload zsh config
alias reload='source ~/.zshrc'
alias zshrc='${EDITOR:-nano} ~/.zshrc'

# Dotfiles management
alias dots='cd ~/dotfiles'
alias dotsave='cd ~/dotfiles && git add -A && git commit -m "Update configs $(date +%Y-%m-%d)" && git push'
alias dotstat='cd ~/dotfiles && git status'
alias dotdiff='cd ~/dotfiles && git diff'

# Show/hide hidden files in Finder (macOS)
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

# ============ Useful Functions ============

# Create directory and cd into it
mkcd() {
    mkdir -p "$1" && cd "$1"
}

# Quick backup of a file
backup() {
    cp "$1" "$1.backup-$(date +%Y%m%d-%H%M%S)"
}

# Extract various archive types
extract() {
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.bz2)   tar xjf "$1"     ;;
            *.tar.gz)    tar xzf "$1"     ;;
            *.bz2)       bunzip2 "$1"     ;;
            *.rar)       unrar x "$1"     ;;
            *.gz)        gunzip "$1"      ;;
            *.tar)       tar xf "$1"      ;;
            *.tbz2)      tar xjf "$1"     ;;
            *.tgz)       tar xzf "$1"     ;;
            *.zip)       unzip "$1"       ;;
            *.Z)         uncompress "$1"  ;;
            *.7z)        7z x "$1"        ;;
            *)           echo "'$1' cannot be extracted" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Find files quickly
f() {
    find . -name "*$1*" 2>/dev/null
}

# Search in history
h() {
    history | grep "$1"
}

# Quick look at CSV files
csv() {
    column -s, -t < "$1" | less -S
}

# Get your public IP
myip() {
    curl -s https://ipinfo.io/ip
    echo
}

# ============ FZF Integration (if installed) ============
# Install with: brew install fzf
if command -v fzf >/dev/null 2>&1; then
    # Fuzzy history search (Ctrl+R)
    source <(fzf --zsh)
    
    # Better file preview
    export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
    
    # Use fd instead of find if available
    if command -v fd >/dev/null 2>&1; then
        export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
    fi
fi

# ============ Better Tab Completion ============
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' # Case insensitive
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"   # Colored completion
zstyle ':completion:*:descriptions' format '%U%F{yellow}%d%f%u'
zstyle ':completion:*:warnings' format '%F{red}No matches found%f'

# ============ Key Bindings ============
bindkey '^[[A' history-search-backward  # Up arrow for history search
bindkey '^[[B' history-search-forward   # Down arrow for history search
bindkey '^[[1;5C' forward-word         # Ctrl+Right to move word forward
bindkey '^[[1;5D' backward-word        # Ctrl+Left to move word backward

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# NVM (Node Version Manager)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# bun completions
[ -s "/Users/zackmckenna/.bun/_bun" ] && source "/Users/zackmckenna/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Add personal bin directory to PATH
export PATH="$HOME/bin:$PATH"


# RunPod Development Environment aliases
alias rp="cd ~/Development/work"
alias rp-start="~/Development/work/runpod-env.sh start"
alias rp-stop="~/Development/work/runpod-env.sh stop"
alias rp-restart="~/Development/work/runpod-env.sh restart"
alias rp-status="~/Development/work/runpod-env.sh status"
alias rp-attach="~/Development/work/runpod-env.sh attach"

# Environment switching
alias rp-local="~/Development/work/runpod-env.sh env local"
alias rp-dev="~/Development/work/runpod-env.sh env dev"
alias rp-staging="~/Development/work/runpod-env.sh env staging"

# Quick development helpers
alias rp-logs="tmux attach -t runpod-dev"
alias rp-console="cd ~/Development/work/console && yarn dev"
alias rp-platform="cd ~/Development/work/runpod && yarn dev"

# Memory analysis
alias memcheck="~/Developer/work/main-ui/console/memcheck.sh"

# Font switching for Alacritty
alias fontswitch="~/bin/fontswitch"
fpath=(~/.zsh/completions $fpath)
autoload -U compinit; compinit
